DROP DATABASE IF EXISTS Sem13Ejer1;
CREATE DATABASE Sem13Ejer1;
USE Sem13Ejer1;
CREATE TABLE Usuarios(
 idUsuario INT NOT NULL AUTO_INCREMENT,
 nombre VARCHAR(100) NOT NULL,
 puntaje INT NOT NULL,
 PRIMARY KEY(idUsuario)
);